---
- hosts: all
  become: true
  become_method: sudo

  tasks:
    - name: Update and upgrade packages on Ubuntu
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Update and upgrade packages on CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
