- hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true

  tasks:
    - name: Ensure system is up-to-date on RedHat/CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
