---
- hosts: all
  become: true    # Ensures that all tasks run with sudo privileges

  tasks:
    - name: Update and upgrade packages on Ubuntu/Debian
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian"

    - name: Update and upgrade packages on CentOS/RedHat
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
