- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure system is up-to-date on Debian/Ubuntu
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Ensure system is up-to-date on RedHat/CentOS
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Ensure system is up-to-date on Fedora
      dnf:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat" and ansible_distribution == "Fedora"

    - name: Ensure system is up-to-date on openSUSE/SUSE
      zypper:
        name: '*'
        state: latest
      when: ansible_os_family == "Suse"

    - name: Check if reboot is required (Debian-based)
      stat:
        path: /var/run/reboot-required
      register: reboot_required
      when: ansible_os_family == "Debian"

    - name: Reboot the system if needed (Debian-based)
      command: /sbin/shutdown -r now "Reboot initiated by Ansible"
      when:
        - ansible_os_family == "Debian"
        - reboot_required.stat.exists
      ignore_errors: true

    - name: Check if reboot is required (RedHat-based)
      shell: "needs-restarting -r"
      register: needs_reboot
      failed_when: needs_reboot.rc not in [0, 1]
      when: ansible_os_family == "RedHat"

    - name: Reboot the system if needed (RedHat-based)
      shell: /sbin/reboot
      when:
        - ansible_os_family == "RedHat"
        - needs_reboot.rc == 1
      ignore_errors: true
